# build
markdown: kramdown
permalink: /blog/:year/:title/
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts_dir: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  name: Poilynx
  description: 你必须知道真相，真相会使你自由。
  author:
    name: Sidney Li
    url: http://www.poilynx.nsscn.org
  lang: en
  favicons:
    - /assets/favicon.png
  topbar:
    toggle: Menu
    right:
      - name: 关于
        url: /about/
      - name: 指南
        url: /guide/
      - name: 博客
        url: /blog/
      - name: GitHub
        url: https://github.com/poilynx/
        class: small button
